trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: RunSimple
    displayName: Run simple example
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'
      - script: |
          npm install
          npm run build
          node examples/simple.js

  - job: RunCompleteWarn
    displayName: Run compete with warnings
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'
      - script: |
          npm install
          npm run build
          node examples/complete-warn.js

  - job: RunCompleteError
    displayName: Run compete with errors
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'
      - script: |
          npm install
          npm run build
          node examples/complete-error.js

  - job: RunWithDate
    displayName: Run example with date included
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'
      - script: |
          npm install
          npm run build
          node examples/with-date.js